export const midiToKey = (midi: number) => {
  switch (midi) {
    case 95:
      return "b4";
    case 94:
      return "a#4";
    case 93:
      return "a4";
    case 92:
      return "g#4";
    case 91:
      return "g4";
    case 90:
      return "f#4";
    case 89:
      return "f4";
    case 88:
      return "e4";
    case 87:
      return "d#4";
    case 86:
      return "d4";
    case 85:
      return "c#4";
    case 84:
      return "c4";
    case 83:
      return "b3";
    case 82:
      return "a#3";
    case 81:
      return "a3";
    case 80:
      return "g#3";
    case 79:
      return "g3";
    case 78:
      return "f#3";
    case 77:
      return "f3";
    case 76:
      return "e3";
    case 75:
      return "d#3";
    case 74:
      return "d3";
    case 73:
      return "c#3";
    case 72:
      return "c3";
    case 71:
      return "b2";
    case 70:
      return "a#2";
    case 69:
      return "a2";
    case 68:
      return "g#2";
    case 67:
      return "g2";
    case 66:
      return "f#2";
    case 65:
      return "f2";
    case 64:
      return "e2";
    case 63:
      return "d#2";
    case 62:
      return "d2";
    case 61:
      return "c#2";
    case 60:
      return "c2";
    case 59:
      return "b1";
    case 58:
      return "a#1";
    case 57:
      return "a1";
    case 56:
      return "g#1";
    case 55:
      return "g1";
    case 54:
      return "f#1";
    case 53:
      return "f1";
    case 52:
      return "e1";
    case 51:
      return "d#1";
    case 50:
      return "d1";
    case 49:
      return "c#1";
    case 48:
      return "c1";
    case 47:
      return "b0";
    case 46:
      return "a#0";
    case 45:
      return "a0";
    case 44:
      return "g#0";
    case 43:
      return "g0";
    case 42:
      return "f#0";
    case 41:
      return "f0";
    case 40:
      return "e0";
    case 39:
      return "d#0";
    case 38:
      return "d0";
    case 37:
      return "c#0";
    case 36:
      return "c0";
    default:
      return undefined;
  }
};
