import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Piano from "views/piano/Piano";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div style={{ height: "100vh" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <p className="text-red-200">tet</p> */}
      <Piano />
    </div>
  );
}
