import Head from "next/head";
import Piano from "views/piano/Piano";
import Settings from "views/ui/settings/Settings";
import CurrentlyPlayingMidi from "views/midiPlayer/CurrentlyPlayingMidi";
import { Canvas } from "@react-three/fiber";
import { Suspense } from "react";
import Ocean from "views/scene/Ocean";
import Lightning from "views/scene/Lightning";
import Controls from "views/scene/Controls";
import SceneSky from "views/scene/Sky";
import { Duck } from "views/scene/Duck";
import Rain from "views/scene/Rain";

export default function Home() {
  return (
    <div style={{ height: "100vh" }}>
      <Head>
        <title>Piano Player</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Settings />
      <CurrentlyPlayingMidi />
      <Canvas shadows className="h-full w-full">
        <Suspense fallback={null}>
          <SceneSky />
          <Piano />
          <Duck />
          <Ocean />
          <Rain />
          <Lightning />
          <Controls />
          {/* <BloomEffect /> */}
        </Suspense>
      </Canvas>
    </div>
  );
}
